[tool.poetry]
name = "viu"
version = "0.1.0"
description = "proyecto"
authors = ["sergio.perezgarcia"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
